[package]
name = "olang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
phf = { features = ["macros"], version = "0.11.2" }
strum = { features = ["derive"], version = "0.26.3" }
thiserror = "2.0.5"
